Update build workflow to test PyPi build

diff --git a/.github/workflows/build_workflow.yml b/.github/workflows/build_workflow.yml
--- a/.github/workflows/build_workflow.yml
+++ b/.github/workflows/build_workflow.yml
@@ -112,6 +112,75 @@ jobs:
                   fail_ci_if_error: true
                   token: ${{ secrets.CODECOV_TOKEN }}
 
+    build-pypi:
+        needs: skip-duplicate-actions
+        if: needs.skip-duplicate-actions.outputs.should_skip != 'true'
+        name: Build (Python ${{ matrix.python-version }})
+        runs-on: "ubuntu-latest"
+        timeout-minutes: 10
+        defaults:
+            run:
+                shell: bash -l {0}
+        strategy:
+            matrix:
+                python-version: ["3.9", "3.10", "3.11", "3.12"]
+        steps:
+            - name: Check out code
+              uses: actions/checkout@v4
+              with:
+                  fetch-depth: 0
+
+            - uses: actions/setup-python@v5
+              name: Install Python
+              with:
+                  python-version: ${{ matrix.python-version }}
+
+            - name: Install dependencies
+              run: |
+                  python -m pip install --upgrade pip
+                  python -m pip install build twine
+
+            - name: Build tarball and wheels
+              run: |
+                  git clean -xdf
+                  git restore -SW .
+                  python -m build
+
+            - name: Check built artifacts
+              run: |
+                  python -m twine check --strict dist/*
+                  pwd
+                  if [ -f dist/xcdat-0.0.0.tar.gz ]; then
+                  echo "❌ INVALID VERSION NUMBER"
+                  exit 1
+                  else
+                  echo "✅ Looks good"
+                  fi
+
+            - uses: actions/upload-artifact@v4
+              with:
+                  name: releases
+                  path: dist
+                    - uses: actions/download-artifact@v4
+              with:
+                  name: releases
+                  path: dist
+
+            - name: List contents of built dist
+              run: |
+                  ls -ltrh
+                  ls -ltrh dist
+
+            - name: Verify the built dist/wheel is valid
+              run: |
+                  python -m pip install --upgrade pip
+                  python -m pip install dist/xcdat*.whl
+                  python -c "import xcdat; print(xcdat.__version__)"
+
+            - name: Run Tests
+              run: |
+                  pytest
+
     # `build-result` is a workaround to skipped matrix jobs in `build` not being considered "successful",
     # which can block PR merges if matrix jobs are required status checks.
     # More info: https://github.com/fkirc/skip-duplicate-actions#how-to-use-skip-check-with-required-matrix-jobs
